name: Telegram Pull Request Notifier
on:
  pull_request:
    branches: [main]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHATID }}
          token: ${{ secrets.BOTTOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
